### ISSUE TITLE
Sensor adjustment menus do not work

### ISSUE THREAD

**Issue by jstck** [berglundinst/NuEVI#24]
The "touch sense" menu works well, but the other adjustment menus do not. The line isn't blinking or moving, but it seems calibration values are being changed (after exiting and refreshing menu, lines have moved and stuff is written to EEPROM).

**Comment by blind** [comment]
It seems display.display() is not called when changing adjust values. I'll look into it.

**Comment by blind** [comment]
Found the bug, fix incoming.
