### ISSUE TITLE
Reduce memory footprint by removing lambdas

### ISSUE THREAD

**Issue by blind** [berglundinst/NuEVI#29]
Ordinary functions+function pointers should be used instead.

**Comment by jstck** [comment]
a) How would functions + function pointers look in this case? A separately defined `updateThisParticularMenuThing` function for each MenuEntry?

b) How do you determine memory footprint for these things? Particularly, how would one tell on the Teensy?

**Comment by blind** [comment]
a) The rotator menu already does this, by having two separate functions as you said.

```
static void rotatorPrioOptionGet(SubMenuRef __unused, char* out, const char** __unused) {
    if (priority) strncpy(out, "ROT", 4);
    else strncpy(out, "MEL", 4);
}

static void rotatorPrioSave(SubMenuRef __unused) {
  writeSetting(PRIO_ADDR,priority);
}

const MenuEntrySub rotatorPrioMenu = {
  MenuType::ESub, "PRIORITY", "MONO PRIO", &priority, 0,1, MenuEntryFlags::EMenuEntryWrap, 
  rotatorPrioOptionGet, rotatorPrioSave, nullptr,
};
```

b) I've been keeping track of global memory use from the build result when compiling via the Arduino app. It seems the lambdas are constructed in runtime, so the structs are stored in RAM when lambas are used, but with normal function pointer they can be kept in ROM.

I did a quick test by extracting the lambdas for the pinky menu, and 40 bytes were saved when both lambdas were converted to normal functions. Now the question is if it's worth the effort if we are going to continue refactoring the menu with classes and stuff anyway.

**Comment by jstck** [comment]
If it is worth doing I guess depends entirely on if we hit the RAM or ROM (flash) limit first, and if either of them will ever happen.
