### ISSUE TITLE
What hardware is used for the pneumatic bite sensor

### ISSUE THREAD

**Issue by tommaier123** [berglundinst/NuEVI#35]
Hello,
I want to build my own NuEvi. Most of the components I can figure out by looking at the schematic or in the code.
But I am not sure what hardware is used for the pneumatic pressure sensor.
Going for the capacitive bite sensor is probably a bit easier but I'd like to try out the pneumatic version.

**Comment by Trasselfrisyr** [comment]
Hi,

The pressure sensor used for PneuBite is the same as for the breath, MP3V5004GP. Fork the tubing and put a car tire valve core in place to make it possible to equalize pressure to ambient air pressure. It’s very important that the system is 100% air tight. I use clear bathroom silicone on joints to keep tight. Also important for the same reason that the mouthpiece bite sensor side is air tight (common problem).

Attaching gerber for PneuBite board. Goes over NuEVI board resistors (double sided tape under the small board is good) and onto pins marked 11 and 12 (if I remember correctly). Put a jumper on those pins also to keep board in place and to ensure connection between those pins (telling the code that the board is installed. Output from the board goes to pin marked A7.

Best,
Johan

**Comment by tommaier123** [comment]
Thanks for the info. Sounds tricky to get everything airtight but I'll give it a try.
Can't wait to start building once I get my hands on a Teensy :)
