### ISSUE TITLE
What hardware is used for vibrato lever

### ISSUE THREAD

**Issue by tommaier123** [berglundinst/NuEVI#36]
Hello,
I've got almost all of the hardware now but I am missing the vibrato lever.
From looking at the code it seems to be a variable capacitor. Is there an off the shelf component that has a lever or did you build one yourself?

**Comment by Trasselfrisyr** [comment]
It’s a bracket bent from 0.4 mm brass sheet/strip with a long M2 screw in place for making the lever. Lip of the bracket is insulated with tape and moving the flexing strip to change capacitance.
